app1:
  scope: 'local'   # local = spain
  nexus_group_id: 'com.domain.group1.app1'
  nexus_artifact_id: 'app_name1'
  nexus_version_dev: '2.0.1'
  nexus_version_uat: '2.0.0'
  nexus_version_pre: '2.0.0'
  nexus_version_pro: '1.9.9'
  nexus_packaging: 'ear'
  ocp_namespace_dev: 'namespace_dev1'
  ocp_namespace_uat: 'namespace_uat1'
  ocp_namespace_pre: 'namespace_pre1'
  ocp_namespace_pro: 'namespace_pro1'
app2:
  scope: 'local'   # local = spain
  nexus_group_id: 'com.domain.group2.app2'
  nexus_artifact_id: 'app_name2'
  nexus_version_dev: '1.0.1'
  nexus_version_uat: '1.0.0'
  nexus_version_pre: '1.0.0'
  nexus_version_pro: '0.9.9'
  nexus_packaging: 'jar'
  ocp_namespace_dev: 'namespace_dev2'
  ocp_namespace_uat: 'namespace_uat2'
  ocp_namespace_pre: 'namespace_pre2'
  ocp_namespace_pro: 'namespace_pro2'
app3:
  scope: 'local'   # local = spain
  nexus_group_id: 'com.domain.group2.app3'
  nexus_artifact_id: 'app_name3'
  nexus_version_dev: '3.0.1'
  nexus_version_uat: '3.0.0'
  nexus_version_pre: '3.0.0'
  nexus_version_pro: '2.9.9'
  nexus_packaging: 'ear'
  ocp_namespace_dev: 'namespace_dev3'
  ocp_namespace_uat: 'namespace_uat3'
  ocp_namespace_pre: 'namespace_pre3'
  ocp_namespace_pro: 'namespace_pro3'
app4:
  scope: 'global'  
  nexus_group_id: 'com.domain.group1.app4'
  nexus_artifact_id: 'app_name4'
  nexus_version_dev: '4.0.1'
  nexus_version_uat: '4.0.0'
  nexus_version_pre: '4.0.0'
  nexus_version_pro: '3.9.9'
  nexus_packaging: 'jar'
  ocp_namespace_dev: 'namespace_dev4'
  ocp_namespace_uat: 'namespace_uat4'
  ocp_namespace_pre: 'namespace_pre4'
  ocp_namespace_pro: 'namespace_pro4'
app5:
  scope: 'global'  
  nexus_group_id: 'com.domain.group2.app5'
  nexus_artifact_id: 'app_name5'
  nexus_version_dev: '1.2.1'
  nexus_version_uat: '1.2.0'
  nexus_version_pre: '1.2.0'
  nexus_version_pro: '0.9.9'
  nexus_packaging: 'ear'
  ocp_namespace_dev: 'namespace_dev5'
  ocp_namespace_uat: 'namespace_uat5'
  ocp_namespace_pre: 'namespace_pre5'
  ocp_namespace_pro: 'namespace_pro5'
app6:
  scope: 'global'   
  nexus_group_id: 'com.domain.group2.app6'
  nexus_artifact_id: 'app_name6'
  nexus_version_dev: '6.5.1'
  nexus_version_uat: '6.5.0'
  nexus_version_pre: '6.5.0'
  nexus_version_pro: '5.5.9'
  nexus_packaging: 'ear'
  ocp_namespace_dev: 'namespace_dev6'
  ocp_namespace_uat: 'namespace_uat6'
  ocp_namespace_pre: 'namespace_pre6'
  ocp_namespace_pro: 'namespace_pro6'
